import Head from 'next/head';
import { useRef } from 'react';
import Image from 'next/image';
import { useRouter } from 'next/router';
import Avatar from '../components/Avatatr';
import Footer from '../components/Footer';
import {
  SearchIcon,
  ViewGridIcon,
  MicrophoneIcon,
} from '@heroicons/react/solid';
export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;
    if (!term) return;
    router.push(`/search?term=${term}`);
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google Lite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">images</p>

          <ViewGridIcon className="h-8 w-8 rounded-full p-2 hover:bg-gray-100 cursor-pointer" />

          <Avatar url="https://ukmadcat.com/wp-content/uploads/2019/04/sleepy-cat.jpg" />
        </div>
      </header>

      {/* Body */}
      <form className="flex flex-col items-center mt-44 flex-grow w-4/5 ">
        <Image
          src="https://www.careerpoint-solutions.com/wp-content/uploads/2015/03/google.jpg"
          width={300}
          height={200}
        />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md border border-gray-200 px-5 py-3 items-center rounded-full">
          <SearchIcon className="w-5 mr-3 text-gray-500" />
          <input
            ref={searchInputRef}
            type="text"
            className="focus:outline-none flex-grow"
          />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button className="btn text-sm" onClick={search}>
            Google Search
          </button>
          <button className="btn text-sm" onClick={search}>
            I'am feeling Lucky'
          </button>
        </div>
      </form>
      {/* footer */}
      <Footer />
    </div>
  );
}
